### ISSUE TITLE
Bonus Section

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/js-euler-palindrome-challenge#19]
I think the bonus should be to take an array of bases and a max and return all of the numbers up to the max that are palindromes in all of the bases in the bases array and the sum (see my version).

If you just ask people to find a number that fits that characteristic for 2,8,10, they can just say "1". and be done.

**Comment by gaand** [comment]
Please see my update.  I changed it to ask for a multi digit number.  There aren't many that are palindromes in bases 2, 8, and 10.

I believe this closes this issue.
