### ISSUE TITLE
Provide additional solutions?

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/js-euler-palindrome-challenge#24]
http://www.mathblog.dk/project-euler-36-palindromic-base-10-2/

**Comment by berziiii** [comment]
http://www.mathblog.dk/project-euler-36-palindromic-base-10-2/

**Comment by gaand** [comment]
dd381623e0d9979928d81770ec39260be299d284 Does brute force strings (ish).

**Comment by gaand** [comment]
fa3b436c79a646c43595c4e5ac078872a0292aa8 implements solutions using strings and not.

Not is about 5 times faster.

I claim this is closed.
