### ISSUE TITLE
Test fails with working code.  Increase timeout.

### ISSUE THREAD

**Issue by aprilsourz** [ga-wdi-boston/js-euler-palindrome-challenge#54]
The first test passes for numbers under 25. The 2nd test for numbers under 1 million does not pass. When I invoke doubleBasePalindromeSum(2, 10, 1000000) in node, I get the result that the test expects which is 872187.

Test Error:

Double base palindromes
   Bases 2 and 10 for numbers less than 10
     ✓ returns 25
   Bases 2 and 10 for numbers less than 1,000,000
     1) returns 872187

 1 passing (2s)
 1 failing

 1) Double base palindromes Bases 2 and 10 for numbers less than 1,000,000 returns 872187:
    Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
 

Warning:  Use --force to continue.

Aborted due to warnings.

**Comment by aprilsourz** [comment]
Here is my code for the challenge.

```js
// change number thas passed in to a different base as a string
function convert (num, base) {
  return (num >>> 0).toString(base)
}

// checks if val is a palindrome, if true returns val as an integer
function checkPalindrome (val) {
  if (val === val.split('').reverse().join('')) {
    return parseInt(val)
  } else {
    return false
  }
}

const doubleBasePalindromeSum = function (base1, base2, upperLimit) {
  let result = 0
  let currentBin = 0
  let currentDec = 0
  for (let i = 0; i < upperLimit; i++) {
    currentBin = convert(i, base1)
    currentDec = convert(i, base2)
    if (checkPalindrome(currentBin) !== false && checkPalindrome(currentDec) !== false) {
      result += parseInt(currentDec)
    }
  }
  return result
}
```

**Comment by jrhorn424** [comment]
We may want to increase the timeout, make a note about the potential failure, or use async to test?
